### ISSUE TITLE
generate view bootstrap - Could not find command "bootstrap".

### ISSUE THREAD

**Issue by grahamja** [constantcontact/jenkins_pipeline_builder#97]
Is the view DSL supposed to be working?

generate view bootstrap
Could not find command "bootstrap".

**Comment by crimsonknave** [comment]
Hmm, it looks like the description says bootstrap, but the keyword is actually 'create'. Can you try ```generate view create``` and see if that works?

**Comment by crimsonknave** [comment]
@grahamja were you able to get it working?

**Comment by grahamja** [comment]
Yes, that was the issue. Thank you!
